base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  collation: utf8_general_ci
  timeout: 5000
  host: localhost
  username: loc_user
  password: 123456789
  pool: 5

development:
  <<: *base
  database: qops_development

test:
  <<: *base
  database: qops_test
  username: <%= ENV['TRAVIS'] ? 'travis' : loc_user %>
  password: <%= ENV['TRAVIS'] ? '' : 123456789 %>
