base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  collation: utf8_general_ci
  timeout: 5000
  host: localhost
  pool: 5

development:
  <<: *base
  database: qops_development

test:
  <<: *base
  database: qops_test
  username: travis
  encoding: utf8
