base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  collation: utf8_general_ci
  timeout: 5000
  host: localhost
  username: <%= ENV['QOPS_DATABASE_PASSWORD'] %>
  password: <%= ENV['QOPS_DATABASE_PASSWORD'] %>
  pool: 20

development:
  <<: *base
  database: qops_development

test:
  <<: *base
  database: qops_test

production:
  <<: *default
  database: qops_production
